name: lipid-docking-benchmark
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - scipy=1.13.1
  - gemmi=0.7.3
  - rdkit=2025.03.3
  - biopython=1.84
  - pyyaml=6.0.2
  - pandas=2.3.1
  - matplotlib=3.10.7
  - cmocean=4.0.3
  - pip:
      - pandamap==4.1.0
      - scienceplots==2.2.0
      - openpyxl==3.1.5
